services:
  server:
    build:
      context: .
    container_name: scheduler_server
    ports:
      - 3002:8000
    command: npm start
    depends_on: 
      - redis
    environment:
      NODE_ENV: production
      PORT: 8000
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis/redis-stack
    container_name: scheduler_redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
      - 8001:8001

volumes:
  redis_data:
